# Generated by Django 3.2.5 on 2021-11-29 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_items_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='category',
        ),
    ]
